[package]
name = "rot_net"
version = "0.1.0"
authors = ["joshawathegrate"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "net"
path = "src/lib.rs"

[dependencies]
timeit="0.1.2"
rand="0.7.3"

[profile.release]
lto = true
opt-level=3
